using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Paper.CSX
{
    [Generator]
    public class CSXSourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            // No initialization needed
        }

        public void Execute(GeneratorExecutionContext context)
        {
            foreach (var additionalFile in context.AdditionalFiles)
            {
                if (additionalFile.Path.EndsWith(".csx"))
                {
                    try
                    {
                        var fileName = Path.GetFileNameWithoutExtension(additionalFile.Path);
                        var componentName = char.ToUpper(fileName[0]) + fileName.Substring(1) + "Component";

                        var fileNode = new CSXFileNode
                        {
                            Path = additionalFile.Path,
                            Namespace = GetNamespaceFromFilePath(additionalFile.Path)
                        };

                        var component = new CSXComponent
                        {
                            Name = componentName
                        };

                        component.Methods.Add(new CSXMethod
                        {
                            Name = fileName,
                            Body = additionalFile.GetText()!.ToString()
                        });

                        fileNode.Components.Add(component);

                        var source = GenerateCode(fileNode);
                        var generatedFileName = componentName + ".generated.cs";
                        context.AddSource(generatedFileName, SourceText.From(source, Encoding.UTF8));
                    }
                    catch (Exception ex)
                    {
                        context.ReportDiagnostic(Diagnostic.Create(
                            new DiagnosticDescriptor(
                                "CSX001",
                                "CSX Generation Error",
                                $"Failed to generate C# code from {Path.GetFileName(additionalFile.Path)}: {ex.Message}",
                                "CSX",
                                DiagnosticSeverity.Error,
                                isEnabledByDefault: true
                            ),
                            Location.Create(additionalFile.Path, new TextSpan(0, 0), new LinePositionSpan(new LinePosition(0, 0), new LinePosition(0, 0)))
                        ));
                    }
                }
            }
        }

        private string GetNamespaceFromFilePath(string filePath)
        {
            var directory = Path.GetDirectoryName(filePath);
            var projectDir = Directory.GetCurrentDirectory();

            if (string.IsNullOrEmpty(directory) || string.IsNullOrEmpty(projectDir))
                return "Paper.Generated";

            var relativePath = Path.GetRelativePath(projectDir, directory);
            var namespaceParts = relativePath.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);

            return string.Join(".", namespaceParts.Select(part =>
                char.ToUpper(part[0]) + part.Substring(1)
            ));
        }

        private string GenerateCode(CSXFileNode fileNode)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using Paper.Core.VirtualDom;");
            sb.AppendLine("using Paper.Core.Styles;");
            sb.AppendLine("using Paper.Core.Hooks;");
            sb.AppendLine();

            sb.AppendLine($"namespace {fileNode.Namespace};");
            sb.AppendLine();

            foreach (var component in fileNode.Components)
            {
                sb.AppendLine($"public static class {component.Name}");
                sb.AppendLine("{");

                foreach (var method in component.Methods)
                {
                    sb.AppendLine($"    public static UINode {method.Name}(Props props)");
                    sb.AppendLine("    {");

                    var (preamble, csxContent) = CSXParser.ExtractPreambleAndJsx(method.Body);
                    if (!string.IsNullOrEmpty(preamble))
                    {
                        foreach (var line in preamble.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries))
                            sb.AppendLine("        " + line.Trim());
                    }
                    if (!string.IsNullOrEmpty(csxContent))
                    {
                        var parsedBody = CSXParser.Parse(csxContent);
                        sb.AppendLine($"        return {parsedBody};");
                    }
                    else
                    {
                        sb.AppendLine("        return UI.Fragment();");
                    }

                    sb.AppendLine("    }");
                    sb.AppendLine();
                }

                sb.AppendLine("}");
                sb.AppendLine();
            }

            return sb.ToString();
        }

        private string? ExtractCSXFromString(string methodBody)
        {
            var cleanBody = methodBody.Trim().TrimEnd(';');

            if (cleanBody.StartsWith("@\""))
            {
                int endIndex = cleanBody.LastIndexOf('"');
                if (endIndex > 0)
                {
                    return cleanBody.Substring(2, endIndex - 2);
                }
            }

            if (cleanBody.StartsWith('"'))
            {
                return cleanBody.TrimStart('"').TrimEnd('"');
            }

            if (cleanBody.Contains('+'))
            {
                var sb = new StringBuilder();
                var parts = cleanBody.Split('+');
                foreach (var part in parts)
                {
                    var trimmed = part.Trim();
                    if (trimmed.StartsWith("@\""))
                    {
                        int endIndex = trimmed.LastIndexOf('"');
                        if (endIndex > 0)
                            sb.Append(trimmed.Substring(2, endIndex - 2));
                    }
                    else if (trimmed.StartsWith('"'))
                    {
                        sb.Append(trimmed.TrimStart('"').TrimEnd('"'));
                    }
                }
                return sb.ToString();
            }

            return null;
        }
    }
}