// <auto-generated />
using Paper.Core.VirtualDom;
using Paper.Core.Styles;
using Paper.Core.Hooks;

namespace Paper.Playground;

public static partial class AppComponent
{
    public static UINode App(Props props)
    {
        var (count, setCount, _) = Hooks.UseState(0);
        var (isActive, setIsActive, _) = Hooks.UseState(false);

        Hooks.UseEffect(() => {
            System.Console.WriteLine($"Count changed to {count}");
            return null;
        }, new object[] { count });

        return UI.Box(new StyleSheet { Display = Display.Flex, FlexDirection = FlexDirection.Column, AlignItems = AlignItems.Center, JustifyContent = JustifyContent.Center, Height = Length.Percent(100), Background = new PaperColour(0.101960786f, 0.101960786f, 0.18039216f, 1f), Padding = new Thickness(16f), BorderRadius = 8f }, 
            UI.Box(new StyleSheet { Background = new PaperColour(0.08627451f, 0.12941177f, 0.24313726f, 1f), Padding = new Thickness(32f), BorderRadius = 8f }, 
                UI.Text("Count: " + count.ToString(), new StyleSheet { FontSize = Length.Px(36), Color = new PaperColour(1f, 0.41960785f, 0.20784314f, 1f), Padding = new Thickness(0f, 0f, 16f, 0f) }), 
                UI.Box(new StyleSheet { Display = Display.Flex, FlexDirection = FlexDirection.Row, Gap = Length.Px(16) }, 
                    UI.Button("Increment", () => setCount(count + 1), new StyleSheet { Background = new PaperColour(0.4f, 0.6f, 1f, 1f), Color = new PaperColour(1f, 1f, 1f, 1f), Padding = new Thickness(12f, 24f), BorderRadius = 6f, FontSize = Length.Px(18) }), 
                    UI.Button("Decrement", () => setCount(count - 1), new StyleSheet { Background = new PaperColour(0.4f, 0.6f, 1f, 1f), Color = new PaperColour(1f, 1f, 1f, 1f), Padding = new Thickness(12f, 24f), BorderRadius = 6f, FontSize = Length.Px(18) }), 
                    UI.Button("Reset", () => setCount(0), new StyleSheet { Background = new PaperColour(0.4f, 0.6f, 1f, 1f), Color = new PaperColour(1f, 1f, 1f, 1f), Padding = new Thickness(12f, 24f), BorderRadius = 6f, FontSize = Length.Px(18) })
                )
            )
        );
    }
}
